[<< 메인으로](https://github.com/AtomicLiquors/Java_Wiki_Chb)

&nbsp;  

# 예외처리 : try-catch
*Exception Handling*

  - 앞서 예외는 비교적 심각성이 낮은 에러라고 하였다.
   
  - 그러나 예외로 인한 비정상 종료를 방지하려면  
   어디까지나 프로그래머가 적절한 코드를 작성하여 예외에 대비해 두어야 한다.

  - 대비하지 못한 예외*uncaught exception*는   
	JVM의 예외처리기*UncaughtExceptionHandler*가 포착하여,  
	예외의 원인을 화면에 출력한다.

&nbsp;  

## try-catch 예시
&nbsp;  
```java
public class ExceptionEx1 {

	public static void main(String[] args) {
		try {
            //예외 발생 가능성이 있는 코드를 넣는다.
			int a = 22;
			int b = 0;
			System.out.println("a + b = " + (a + b));
			System.out.println("a - b = " + (a - b));
			System.out.println("a * b = " + (a * b));
			System.out.println("a / b = " + (a / b));
            //예외가 발생하면, 다음 구문은 실행되지 않는다.
			System.out.println("계산 완료!");
            
		} catch (Exception e) {
            //예외가 일어나면 실행되는 영역. 
            //e는 발생하는 예외 객체를 가리키는 참조변수다.

			//System.out.println("예외 메시지 : " + e.getMessage());
			System.err.println("예외 메시지 : " + e.getMessage());
			//System.out을 안 쓰고 System.err를 쓴 점에 주목해 달라.
            //err를 쓴 경우, 다른 에러 메시지처럼 콘솔에서 빨간색으로 출력된다.

            e.printStackTrace(); 
			//예외가 일어나면 추적(history)내용까지 출력. 디버깅할 때 많이 쓴다.
		}
		try{
			System.out.println("try 실행");
		} finally {//try-catch-finally
			//예외가 있든 없든 무조건 실행하는 구문이다.
			System.out.println("finally 실행");
		}	
	}
}
```


### 예외 참조변수 e와 자주 쓰이는 메소드
- printStacktrace() :   
     예외 발생 당시의 호출스택에 있었떤 메서드 정보와 예외 메시지를 화면에 출력한다.
- getMessage() :  
  발생한 예외 클래스의 인스턴스에 저장된 메시지를 얻을 수 있다.

&nbsp; 
### 여러 개의 catch 블럭
다양한 타입의 에러를 감지하고 알맞은 코드를 실행한다.
```java
public class ExceptionEx1 {

	public static void main(String[] args) {
		try {
            
		}catch (Exception1 e1) {
            //예외 타입 1번을 포착하면 코드를 실행한다.
            //포착하지 못하면, 다음 블럭으로 넘어간다.
             e1.printStackTrace(); 
		}catch (Exception2 e2) {
            //예외 타입 2번을 포착하면 코드를 실행한다.
            //포착하지 못하면, 다음 블럭으로 넘어간다.
             e2.printStackTrace(); 
		}catch(Exception e){
            //그동안 줄곧 사용해 온 Exception은 모든 예외의 조상 클래스다.
            //마지막 블럭에 Exception을 넣어, 
            //앞선 두 가지 타입 외의 모든 예외를 포착한다.
            e.printStackTrace();
        }	
	}
}
```

&nbsp; 
### 멀티 catch블럭
JDK 1.7부터 지원된다. '|'기호로 여러 개의 catch 블럭을 하나로 합칠 수 있다.  
이 때, '|'는 논리 연산자가 아닌 기호일 뿐이다.

```java
public class ExceptionEx1 {

	public static void main(String[] args) {
		try {
            
		}catch (Exception1 | Exception2 e) {
            //예외 타입 1번 또는 예외 타입 2번을 포착한다.
             e.printStackTrace(); 
		}
	}
}
```
&nbsp;  
**멀티 catch블럭의 제약사항**
- '|'로 연결된 예외 클래스가 서로 부모-자식 관계라면 컴파일 에러가 발생한다.  
  
  그럴 바에야 부모 클래스 하나만 쓰면 되는 거고,  
  불필요한 코드 중복이기 때문에 에러로 취급한다.
  
- 참조변수 e는 '|'로 연결된 클래스들의 공통된 부모 클래스만 접근할 수 있다.  
  
   많은 예외 클래스 중 실제로 어떤 예외가 발생했는지 특정할 수 없기 때문에,  
   공통된 부모에 대한 접근만 허용한다.
- 멀티 catch블럭에 선언된 참조변수 e는 상수며, 값을 변경할 수 없다.  
  
    여러 catch블럭이 하나의 참조변수를 공유하기 때문에 두는 제약이다.

  &nbsp;   
> 다만 실제로 멀티catch를 쓰는 상황은 코드를 간단히 하는 정도일 것이기 때문에,  
> 이런 제약사항에 대해 너무 고민하지 않기를 바란다.

  &nbsp;   
